### ISSUE TITLE
repo organization

### ISSUE THREAD

**Issue by mtfurlan** [br101/zephyr-dw3000-decadriver#11]
Every other zephyr module I've seen only has `module.yml` inside the zephyr dir, so it's weird that this one puts everything there

Examples:
* https://github.com/zephyrproject-rtos/fatfs
* https://github.com/zephyrproject-rtos/littlefs
* https://github.com/zephyrproject-rtos/trusted-firmware-a
* https://github.com/u-blox/ubxlib/tree/master/zephyr
  * they have a little more cause they are targeting not only zephyr and are doing some weird stuff

If I do a PR to reorganize would you have any issues?
I'm confident it won't break anything if you're using this via `west.yml`, and I believe it won't break if you're appending to `ZEPHYR_EXTRA_MODULES` manually

**Comment by br101** [comment]
Sure, go ahead, every contribution is very much appreciated!
