### ISSUE TITLE
Pin bindings in README deprecated

### ISSUE THREAD

**Issue by pascal-kuschkowitz** [br101/zephyr-dw3000-decadriver#16]
## Excerpt from release notes `3.2` of zephyr

Various bindings have had ``foo-pin`` properties deprecated. For example, :dtcompatible:`nordic,nrf-qspi` has a deprecated ``sck-pin`` property. Uses of such properties should be replaced with pinctrl equivalents; see :dtcompatible:`nordic,nrfpinctrl`.

**Comment by br101** [comment]
Updated. Is that all, or do I have to use pinctrl also for the GPIOs we use?
