### ISSUE TITLE
I/O pin association

### ISSUE THREAD

**Issue by wpless56atAC** [br101/zephyr-dw3000-decadriver#18]
In your .dts(i) file you are selecting pins P0,28 for SCK, P0,31 for MOSI and P0,3 for MISO.
As you are also referencing the DW3001CDK in your Readme, I am assuming that your Zephyr driver was meant for that HW.
The schematics that I have for the DW3001CDK show P0.3 for SCK, P0,8 for MOSI and P0,29 for MISO.

This discrepancy indicates that either your driver is for another HW, or the schematics that I have (11-9-2021) has another revision than that, which you used.

Pls., let me know, for which HW (-revision) you have developed and tested the zephyr driver.

Thanks in advance,
Wilfried

**Comment by wpless56atAC** [comment]
I have to revise my question. It appears that your setup was a nRF52833DK plus a DW3000EVB. 
Still there seems to be a I/O pin assignment discrepancy. The hardware description manual of the nRF52833DK assigns the following I/O to P4 (equivalent to CON1 of the Arduino interface:
SPICLK: pin #6 <=> P0.25
MOSI:  pin #4 <=> P0.23
MISO: pin #5  <=> P0.24

As written above, the assignment for (not only) SPICLK, MOSI and MISO is different from the assignment in .dts.

Obviously, I still seem to miss something.

BR,
Wilfried

**Comment by br101** [comment]
Hi, the example in the README really is only an example. It coincides with a custom board I use, but its not related to DW3000EVB. So you have to adapt it to your own HW setup.
