### ISSUE TITLE
definition of CONFIG_DW3000 and CONFIG_DW3000_CHIP_DW3000

### ISSUE THREAD

**Issue by wpless56atAC** [br101/zephyr-dw3000-decadriver#20]
where are 
CONFIG_DW3000 and
CONFIG_DW3000_CHIP_DW3000
defined?

There is no directory dw3000-decadriver that you refer to in the Readme in the line
list(APPEND ZEPHYR_EXTRA_MODULES ${CMAKE_CURRENT_SOURCE_DIR}/dw3000-decadriver/)

Rgds.,
Wilfried

**Comment by br101** [comment]
thats the directory where you checkout the zephyr-dw3000-decadriver repository.
the configs are usually defined in your applications prj.conf

**Comment by wpless56atAC** [comment]
… just found:

It has been tested with the following Qorvo chips:

  *   DW3110 (DEVID: 0xDECA0302) on DWM3000
  *   DW3120 (DEVID: 0xDECA0312)


So, the fata error must have some other reason.

Mit freundlichen Grüßen / Best regards
i.A. Wilfried Pless
Software Developer
Atlas Copco Tools Central Europe GmbH
Visitor Address: Langemarckstr. 35
D-45141 Essen
Postal Address: 10 02 44
D-45002 Essen
E-mail:   ***@***.******@***.***>
Geschäftsführer: Claus Schiedek, Peter Edmonds, Thomas Hülsmann
HRB Essen 5096, UID: DE811155641
Visit Atlas Copco at:   www.atlascopco.com<https://www.atlascopco.com/de-de>
Follow us at:   Facebook<https://facebook.com/AtlasCopcoDeutschland/?ref=br_rs> - LinkedIn<https://linkedin.com/company/atlas-copco/> - Xing<https://xing.com/companies/atlascopcotoolscentraleuropegmbh> - Twitter<https://twitter.com/AtlasCopcoGroup> - Youtube<https://youtube.com/channel/UCzsUHfLsnuLDlWIRODw8yAQ> - Instagram<https://instagram.com/atlascopcogroup/>
Home of Industrial Ideas
<https://app.mailtastic.de/api/li/c186e271-61fd-4b64-b8b3-1b1b39ae1bd1>

From: Wilfried Pless
Sent: Wednesday, November 13, 2024 4:50 PM
To: br101/zephyr-dw3000-decadriver ***@***.***>
Subject: RE: [br101/zephyr-dw3000-decadriver] definition of CONFIG_DW3000 and CONFIG_DW3000_CHIP_DW3000 (Issue #20)

Hello Bruno,

thanks for all the effort you have put into this endeavor and your willingness to support. My questions have obviously shown that I am a newbie in this area and at least you did not just ignore me.

Meanwhile I have a working setup consisting of an nRF52833DK + DWM3000EVB and an all-in-one development kit DWM3001CDK.
“Workinng” here means: I can read out the device IDs (DECA0302, which indicates a Qorvo 3120 chip).
Being too ambitious after that success, I wanted to run the simple TX/RX application with two DWM3001CDK sets.
Unfortunately that ended in a ZEPHYR FATAL ERROR 4 😊.

Is there possibly anything in the code that I need to set or unset to make that code run on a nrf52833 / Qorvo 3120 combination?

Mit freundlichen Grüßen / Best regards
i.A. Wilfried Pless
Software Developer
Atlas Copco Tools Central Europe GmbH
Visitor Address: Langemarckstr. 35
D-45141 Essen
Postal Address: 10 02 44
D-45002 Essen
E-mail:   ***@***.******@***.***>
Geschäftsführer: Claus Schiedek, Peter Edmonds, Thomas Hülsmann
HRB Essen 5096, UID: DE811155641
Visit Atlas Copco at:   www.atlascopco.com<https://www.atlascopco.com/de-de>
Follow us at:   Facebook<https://facebook.com/AtlasCopcoDeutschland/?ref=br_rs> - LinkedIn<https://linkedin.com/company/atlas-copco/> - Xing<https://xing.com/companies/atlascopcotoolscentraleuropegmbh> - Twitter<https://twitter.com/AtlasCopcoGroup> - Youtube<https://youtube.com/channel/UCzsUHfLsnuLDlWIRODw8yAQ> - Instagram<https://instagram.com/atlascopcogroup/>
Home of Industrial Ideas
<https://app.mailtastic.de/api/li/c186e271-61fd-4b64-b8b3-1b1b39ae1bd1>
