### ISSUE TITLE
Bug in dw3000_spi_wakeup()

### ISSUE THREAD

**Issue by gicutri** [br101/zephyr-dw3000-decadriver#7]
In the function dw3000_spi_wakeup() the CS pin is driven high for 500ms but, according to the user manual, it should be pulled low. I tried this fix and now the IC is correctly waking up.

**Comment by br101** [comment]
Yes that seems to be a mistake. Could you make a pull request?

**Comment by gicutri** [comment]
I can do it if you give me "create branch" permission. I would like to not create a fork for just this simple change.

**Comment by br101** [comment]
Thats how its usually done in github... but let me see maybe i can do it myself
