### ISSUE TITLE
Support for Cortex M33

### ISSUE THREAD

**Issue by KyleKotowick** [br101/zephyr-dw3000-decadriver#8]
I'm working with this using the nRF5340, which has an M33 processor. It seems that the library selection is [hardcoded](https://github.com/br101/zephyr-dw3000-decadriver/blob/8aeccb1204b99e0283d300da5d55019b3dbb7b78/zephyr/dwt_uwb_driver/CMakeLists.txt#L3-L7) for Cortex M4 processors.

Is there a way to determine which type of processor the board uses and select the library based on that?

**Comment by KyleKotowick** [comment]
Is this documented somewhere? Which functions the binary includes and which it does not?

**Comment by Frank-Buss** [comment]
My company has it working for nRF5340, with Zephyr and their latest SDK. I needed the following libraries:
```
zephyr_library_import(dwtlib ${drivers_dir}/uwb/Qorvo/Libs/dwt_uwb_driver/lib/libdwt_uwb_driver-m4-hfp-6.0.14.a)
zephyr_library_import(niqlib ${drivers_dir}/uwb/Qorvo/Libs/niq/libniq-m4-hfp-1.1.0.0.a)
zephyr_library_import(maclib ${drivers_dir}/uwb/Qorvo/Libs/uwbstack/uwbstack_lib/lib/cmsis_v1/embedded_mac/libembedded_mac_arm-m4-hfp_R11.9.2.a)
```
and also the settings `CONFIG_FPU=y` and `CONFIG_FP_HARDABI=y`. Maybe works for this project as well. Or you could also port their SDK, needs a few weeks.

**Comment by br101** [comment]
> I'm not quite following. In the `lib` directory it has M33 binaries as well. Which components are missing?

Oh, okay. Sorry, I don't actively use this project since quite a while... Then, it should be possible to adapt to use these libraries in that case...

**Comment by vdjajaj** [comment]
I have added the pull request that allows for the usage of the currently newest nRF Connect SDK (version 2.6.0) and the ability to use the nRF5340 SoC. However, it wasn't extensively tested (it successfully compiles, and I have tested if it reads the DW3000 module's DEV_ID and if dwt_check_dev_id API function returns DWT_SUCCESS and it does).

**Comment by br101** [comment]
Thank you, it's merged!
